apiVersion: v1
kind: Secret
metadata:
  name: {{ include "netnynja.fullname" . }}-secrets
  labels:
    {{- include "netnynja.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-url: "postgresql://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ include "netnynja.postgresHost" . }}:5432/{{ .Values.postgresql.auth.database }}"
  redis-url: "redis://:{{ .Values.redis.auth.password }}@{{ include "netnynja.redisHost" . }}:6379"
  jwt-secret: "{{ randAlphaNum 64 }}"
